version: '3.8'

services:
  # NoSQL DB (MongoDB)
  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - mongodb_data:/data/db

  # Python Application
  app:
    build: ./app
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - db

networks:
  my_network:
    driver: bridge

volumes:
  mongodb_data:
